// Mocks generated by Mockito 5.4.3 from annotations
// in rinjani_visitor/test/features/product/view_model/search_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rinjani_visitor/features/product/data/product_repository_impl.dart'
    as _i4;
import 'package:rinjani_visitor/features/product/data/source/mock.dart' as _i2;
import 'package:rinjani_visitor/features/product/domain/category_enum.dart'
    as _i6;
import 'package:rinjani_visitor/features/product/domain/entity/product.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataSourceMock_0 extends _i1.SmartFake
    implements _i2.DataSourceMock {
  _FakeDataSourceMock_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductEntity_1 extends _i1.SmartFake implements _i3.ProductEntity {
  _FakeProductEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepositoryImpl extends _i1.Mock
    implements _i4.ProductRepositoryImpl {
  MockProductRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DataSourceMock get remote => (super.noSuchMethod(
        Invocation.getter(#remote),
        returnValue: _FakeDataSourceMock_0(
          this,
          Invocation.getter(#remote),
        ),
      ) as _i2.DataSourceMock);

  @override
  _i5.Future<_i3.ProductEntity> bookingPackage({
    required String? packageId,
    List<String>? addOns,
    String? paymentMethod,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookingPackage,
          [],
          {
            #packageId: packageId,
            #addOns: addOns,
            #paymentMethod: paymentMethod,
          },
        ),
        returnValue: _i5.Future<_i3.ProductEntity>.value(_FakeProductEntity_1(
          this,
          Invocation.method(
            #bookingPackage,
            [],
            {
              #packageId: packageId,
              #addOns: addOns,
              #paymentMethod: paymentMethod,
            },
          ),
        )),
      ) as _i5.Future<_i3.ProductEntity>);

  @override
  _i5.Future<void> cancelPackage({required String? packageId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelPackage,
          [],
          {#packageId: packageId},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ProductEntity> getPackageDetail(
          {required String? packageId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackageDetail,
          [],
          {#packageId: packageId},
        ),
        returnValue: _i5.Future<_i3.ProductEntity>.value(_FakeProductEntity_1(
          this,
          Invocation.method(
            #getPackageDetail,
            [],
            {#packageId: packageId},
          ),
        )),
      ) as _i5.Future<_i3.ProductEntity>);

  @override
  _i5.Future<List<_i3.ProductEntity>> getPackages({
    int? pages = 1,
    int? itemsPerPage = 10,
    _i6.ProductCategory? category,
    String? query = r'',
    String? avaiability,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPackages,
          [],
          {
            #pages: pages,
            #itemsPerPage: itemsPerPage,
            #category: category,
            #query: query,
            #avaiability: avaiability,
          },
        ),
        returnValue:
            _i5.Future<List<_i3.ProductEntity>>.value(<_i3.ProductEntity>[]),
      ) as _i5.Future<List<_i3.ProductEntity>>);
}
